language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py build develop
# command to run tests
script:
  - python -m pytest tests/ --cov-report term-missing --cov networkanalysis  
after_success:
  - codecov
